/**
 * ACC 2026 队服订购 — 订购表单一次性设置脚本 / one-off setup for the kit order Google Form.
 *
 * 用法 How to run
 *   1. 打开 https://script.google.com → 新建项目，把整个文件粘贴进去（覆盖默认内容）。
 *   2. 选择函数 `setupKitOrderForm`，点「运行」，按提示授权（表单 + 表格权限）。
 *   3. 运行日志里会给出新建的「回复」表格链接；再把 Form 里「付款截图」题的「必填」手动打开
 *      （Apps Script 无法修改文件上传题的必填项）。
 *
 * 做什么 What it does
 *   - 删除「订单明细」「总件数」，改成与内部订购表一致的列：
 *     分体上衣 / 分体裤 / 马甲 各自的 版型、尺码、数量（+ 马甲颜色）和一个「其他尺码」栏。
 *   - 把 订单号、应付金额、付款方式、会员、姓名、邮箱、电话、确认 设为必填；邮箱加格式验证；
 *     数量限定为 1–10 的整数；补全各题说明与确认条款；设置提交后的确认消息。
 *   - 新建「回复」Google 表格并关联到表单。
 *
 * 只运行一次：再次运行会因为检测到已存在的新题而停止，不会重复添加。
 * 题目标题里的前几个字（如「分体上衣尺码」）与内部表表头一致，网站的预填链接依赖选项文字，
 * 选项文字请不要手动改动。
 */

const FORM_ID = '14uEyUSBQekei2rZj8n6f2oiUB3r2xeSCzbujCJ_eXMQ';

const SIZES = ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'];
const CUTS = ['男款', '女款'];
const VEST_COLORS = ['黑色', '白色'];

const TERMS_TEXT = [
  '① 模特图为样衣，成品以官网设计图为准（ACC Logo 样式有微调），实物与效果图会有出入。',
  '② 仅限质量问题可换，其余一律不退不换（包括尺码选错），请务必对照尺码表。',
  '③ 仅限慕尼黑自提，不邮寄；预计 12 月中旬到货，取货方式将在微信群通知。',
  '④ 个人信息与付款截图通过 Google 表单收集，仅用于本次队服订购及核对付款。',
  '',
  '① The model wears a sample; the final kit follows the design drawings and will differ slightly from the photos.',
  '② Exchange for quality defects only; otherwise no returns or exchanges, wrong size included.',
  '③ Pick-up in Munich only, no shipping; expected mid-December.',
  '④ Your data and payment proof are collected through this Google Form and used only for this order.',
].join('\n');

const CONFIRMATION_MESSAGE =
  '感谢订购！我们会核对付款，并通过邮件或微信群通知您。请保存好订单号。\n\n' +
  '最后一步：请添加工作人员 Ronnie 的微信，让他拉您进订购群（到货时间、取货时间和地点都在群里通知）。添加时请备注您的姓名和订单号。\n' +
  '微信二维码：https://www.across-cc.de/images/uniform/contact-wechat.webp\n\n' +
  'Thank you! We will verify your payment and contact you by email or via the WeChat group. Please keep your order code.\n\n' +
  'Last step: add our team member Ronnie on WeChat and ask to be added to the order group (arrival and pick-up time and place are announced there). Please put your name and order code in the request note.\n' +
  'WeChat QR code: https://www.across-cc.de/images/uniform/contact-wechat.webp';

/** Final question order, by title prefix. */
const ORDER = [
  '订单号',
  '分体上衣版型', '分体上衣尺码', '分体上衣数量',
  '分体裤版型', '分体裤尺码', '分体裤数量',
  '马甲版型', '马甲颜色', '马甲尺码', '马甲数量',
  '其他尺码',
  '应付金额', '付款方式', '是否 ACC 会员',
  '姓名', '邮箱', '电话', '微信名/备注名',
  '付款截图', '备注', '确认',
];

function setupKitOrderForm() {
  const form = FormApp.openById(FORM_ID);

  if (form.getItems().some((item) => item.getTitle().indexOf('分体上衣尺码') === 0)) {
    throw new Error('这个表单已经设置过了（已有「分体上衣尺码」）。/ Already set up.');
  }

  removeOld(form, ['订单明细', '总件数']);
  addNewQuestions(form);
  tidyExisting(form);
  reorder(form);

  form.setConfirmationMessage(CONFIRMATION_MESSAGE);
  form.setCollectEmail(false);
  form.setLimitOneResponsePerUser(false);
  form.setAllowResponseEdits(false);

  const sheet = SpreadsheetApp.create('ACC 2026 队服订购 — 回复 / Kit Order Responses');
  form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId());

  Logger.log('完成 Done. 回复表格 Responses sheet: ' + sheet.getUrl());
  Logger.log('请到表单手动打开「付款截图」题的「必填」。/ Turn on "Required" for the upload question by hand.');
}

function removeOld(form, titlePrefixes) {
  titlePrefixes.forEach((prefix) => {
    const item = findOne(form, prefix);
    form.deleteItem(item);
  });
}

function addNewQuestions(form) {
  const itemGroups = [
    { key: '分体上衣', en: 'Jersey' },
    { key: '分体裤', en: 'Bib shorts' },
    { key: '马甲', en: 'Vest' },
  ];

  itemGroups.forEach((group) => {
    form.addMultipleChoiceItem()
      .setTitle(group.key + '版型 ' + group.en + ' cut')
      .setHelpText('由订购页自动填写。Filled in by the order page.')
      .setChoiceValues(CUTS)
      .setRequired(false);

    if (group.key === '马甲') {
      form.addListItem()
        .setTitle('马甲颜色 Vest colour')
        .setChoiceValues(VEST_COLORS)
        .setRequired(false);
    }

    form.addListItem()
      .setTitle(group.key + '尺码 ' + group.en + ' size')
      .setChoiceValues(SIZES)
      .setRequired(false);

    form.addTextItem()
      .setTitle(group.key + '数量 ' + group.en + ' quantity')
      .setValidation(
        FormApp.createTextValidation()
          .setHelpText('请输入 1–10 的整数 / Enter a whole number from 1 to 10')
          .requireNumberBetween(1, 10)
          .build()
      )
      .setRequired(false);
  });

  form.addParagraphTextItem()
    .setTitle('其他尺码 Additional items')
    .setHelpText(
      '由订购页自动填写：同一款式要订不同尺码（或另一种马甲颜色）时，多出来的写在这里，' +
      '每行格式：款式 | 版型 | 颜色/尺码 | 数量。工作人员会手动汇总。\n' +
      'Filled in by the order page when you order a second size (or vest colour) of the same item.'
    )
    .setRequired(false);
}

function tidyExisting(form) {
  requireText(form, '订单号', true,
    '由订购页自动生成，请勿修改。转账时请把它写在备注里（SEPA 的 Verwendungszweck）。\n' +
    'Generated by the order page — do not change it. Put it in your payment note.');

  requireText(form, '应付金额', true,
    '数字，已含转运费，不含货币符号；币种由「付款方式」决定。\n' +
    'A number, transfer fee included, without a currency sign; the currency follows the payment method.');

  setRequired(findOne(form, '付款方式'), true);

  const membership = findOne(form, '是否 ACC 会员');
  membership.setHelpText('自行选择，我们会事后核对会员身份。Self-declared, verified afterwards.');
  setRequired(membership, true);

  requireText(form, '姓名', true);

  const email = findOne(form, '邮箱').asTextItem();
  email.setValidation(FormApp.createTextValidation().requireTextIsEmail().build());
  email.setRequired(true);

  requireText(form, '电话', true,
    '请含国家区号，例如 +49。Please include the country code.');

  const wechat = findOne(form, '微信号').asTextItem();
  wechat.setTitle('微信名/备注名 WeChat name');
  wechat.setRequired(false);

  const upload = findOne(form, '付款截图');
  try {
    upload.setHelpText('请上传转账或支付宝付款的截图。Upload a screenshot of your payment.');
  } catch (e) {
    Logger.log('无法设置上传题说明 Could not set the upload help text: ' + e);
  }

  const confirmation = findOne(form, '确认').asCheckboxItem();
  confirmation.setHelpText(TERMS_TEXT);
  confirmation.setRequired(true);
}

function reorder(form) {
  ORDER.forEach((prefix, index) => {
    form.moveItem(findOne(form, prefix), index);
  });
}

// ---------------------------------------------------------------- helpers

function findOne(form, titlePrefix) {
  const matches = form.getItems().filter((item) => item.getTitle().indexOf(titlePrefix) === 0);
  if (matches.length !== 1) {
    throw new Error('找不到唯一的题目「' + titlePrefix + '」，找到 ' + matches.length + ' 个。');
  }
  return matches[0];
}

function requireText(form, titlePrefix, required, helpText) {
  const item = findOne(form, titlePrefix);
  if (helpText) item.setHelpText(helpText);
  setRequired(item, required);
}

function setRequired(item, required) {
  const type = item.getType();
  if (type === FormApp.ItemType.TEXT) item.asTextItem().setRequired(required);
  else if (type === FormApp.ItemType.PARAGRAPH_TEXT) item.asParagraphTextItem().setRequired(required);
  else if (type === FormApp.ItemType.MULTIPLE_CHOICE) item.asMultipleChoiceItem().setRequired(required);
  else if (type === FormApp.ItemType.LIST) item.asListItem().setRequired(required);
  else if (type === FormApp.ItemType.CHECKBOX) item.asCheckboxItem().setRequired(required);
  else Logger.log('跳过必填设置 Skipped required for type ' + type + ': ' + item.getTitle());
}
